### ISSUE TITLE
Security vulnerability?

### ISSUE THREAD

**Issue by robcarey** [Jako/LogRequest#5]
I noticed when logging in to the manager today that I was getting a javascript alert prompt with just a "1" displayed.  It became evident that this javascript event was being fired from logrequest entries  in the dashboard!  A little scary to say the least.

Upon disabling logrequest immediately and reviewing the data, it doesn't appear to me that anything was compromised - if anyone can see any evidence to the contrary then please let me know, but this possibility should be reviewed and addressed.

A text file dump of the records in question from logrequest table is attached

[logrequest_dump.txt](https://github.com/Jako/LogRequest/files/5623421/logrequest_dump.txt)

**Comment by Jako** [comment]
Thanks for posting the security issue. I will look into this the next days.

**Comment by robcarey** [comment]
Thank you for all you do for the MODX community - you're an asset to us all!

**Comment by Jako** [comment]
Fixed with 1.0.2
